name: Bigyahu
favicon: null
layout_spectrum: 0.6194836157374084
typography_spectrum: 0.7543819593265653
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9451600471511483
  lightness: 0.11740537406876683
  saturation: 0.5342618173453957
  rhythmicContrast: 0.49228482227772474
purpose: []
